# Copyright (c) 2021 Red Hat, Inc.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-policy-metrics
  labels:
    app: {{ template "grc.name" . }}
    chart: {{ template "grc.chart" . }}
    component: "ocm-policy-metrics"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "grc.name" . }}
    helm.sh/chart: {{ template "grc.chart" . }}
spec:
  ports:
    - port: 8443
      targetPort: 8383
      protocol: TCP
      name: https
  selector:
    app: {{ template "grc.name" . }}
    component: "ocm-policy-propagator"
    release: {{ .Release.Name }}
  sessionAffinity: ClientIP
